// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ReservationApi.Infrastructure.Data;

#nullable disable

namespace ReservationApi.Infrastructure.Data.Migrations
{
    [DbContext(typeof(ReservationServiceDBContext))]
    partial class ReservationServiceDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ReservationApi.Domain.Entities.Booking", b =>
                {
                    b.Property<Guid>("BookingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("booking_Id");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("account_Id");

                    b.Property<DateTime>("BookingDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("bookingDate");

                    b.Property<Guid>("BookingStatusId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("bookingStatus_Id");

                    b.Property<Guid>("BookingTypeId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("bookingType_Id");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("createAt");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("notes");

                    b.Property<Guid>("PaymentTypeId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("paymentType_Id");

                    b.Property<Guid>("PointRuleId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("pointRule_Id");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("totalAmount");

                    b.Property<DateTime>("UpdateAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updatedAt");

                    b.Property<Guid>("VoucherId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("voucher_Id");

                    b.Property<bool>("isPaid")
                        .HasColumnType("bit")
                        .HasColumnName("isPaid");

                    b.HasKey("BookingId");

                    b.HasIndex("BookingStatusId");

                    b.HasIndex("BookingTypeId");

                    b.HasIndex("PaymentTypeId");

                    b.HasIndex("PointRuleId");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("ReservationApi.Domain.Entities.BookingStatus", b =>
                {
                    b.Property<Guid>("BookingStatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("bookingStatus_Id");

                    b.Property<string>("BookingStatusName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("bookingStatus_name");

                    b.Property<bool>("isDeleted")
                        .HasColumnType("bit");

                    b.HasKey("BookingStatusId");

                    b.ToTable("BookingStatuses");
                });

            modelBuilder.Entity("ReservationApi.Domain.Entities.BookingType", b =>
                {
                    b.Property<Guid>("BookingTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("bookingType_Id");

                    b.Property<string>("BookingTypeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("bookingTpye_name");

                    b.Property<bool>("isDeleted")
                        .HasColumnType("bit");

                    b.HasKey("BookingTypeId");

                    b.ToTable("BookingTypes");
                });

            modelBuilder.Entity("ReservationApi.Domain.Entities.PaymentType", b =>
                {
                    b.Property<Guid>("PaymentTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("paymentType_Id");

                    b.Property<string>("PaymentTypeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("paymentType_name");

                    b.Property<bool>("isDeleted")
                        .HasColumnType("bit");

                    b.HasKey("PaymentTypeId");

                    b.ToTable("PaymentTypes");
                });

            modelBuilder.Entity("ReservationApi.Domain.Entities.PointRule", b =>
                {
                    b.Property<Guid>("PointRuleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("pointRule_Id");

                    b.Property<int>("PointRuleRatio")
                        .HasColumnType("int")
                        .HasColumnName("pointRuleRatio");

                    b.Property<bool>("isDeleted")
                        .HasColumnType("bit");

                    b.HasKey("PointRuleId");

                    b.ToTable("PointRules");
                });

            modelBuilder.Entity("ReservationApi.Domain.Entities.Booking", b =>
                {
                    b.HasOne("ReservationApi.Domain.Entities.BookingStatus", "BookingStatus")
                        .WithMany("Bookings")
                        .HasForeignKey("BookingStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ReservationApi.Domain.Entities.BookingType", "BookingType")
                        .WithMany("Bookings")
                        .HasForeignKey("BookingTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ReservationApi.Domain.Entities.PaymentType", "PaymentType")
                        .WithMany("Bookings")
                        .HasForeignKey("PaymentTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ReservationApi.Domain.Entities.PointRule", "PointRule")
                        .WithMany("Bookings")
                        .HasForeignKey("PointRuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BookingStatus");

                    b.Navigation("BookingType");

                    b.Navigation("PaymentType");

                    b.Navigation("PointRule");
                });

            modelBuilder.Entity("ReservationApi.Domain.Entities.BookingStatus", b =>
                {
                    b.Navigation("Bookings");
                });

            modelBuilder.Entity("ReservationApi.Domain.Entities.BookingType", b =>
                {
                    b.Navigation("Bookings");
                });

            modelBuilder.Entity("ReservationApi.Domain.Entities.PaymentType", b =>
                {
                    b.Navigation("Bookings");
                });

            modelBuilder.Entity("ReservationApi.Domain.Entities.PointRule", b =>
                {
                    b.Navigation("Bookings");
                });
#pragma warning restore 612, 618
        }
    }
}
