using PSPS.Domain.Entities;
using PSPS.Infrastructure.DependencyInjection;
var builder = WebApplication.CreateBuilder(args);
builder.Services.AddControllers();
builder.Services.AddEndpointsApiExplorer();
builder.Services.AddSwaggerGen();
builder.Services.AddInfrastructureService(builder.Configuration);
builder.Services.Configure<EmailSetting>(builder.Configuration.GetSection("EmailSettings"));
var app = builder.Build();
app.UseSwagger();
app.UseSwaggerUI();
app.UserInfrastructurePolicy();
app.UseHttpsRedirection();
app.UseAuthorization();
app.MapControllers();
app.Run();
