// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PSBS.HealthCareApi.Infrastructure.Data;

#nullable disable

namespace PSBS.HealthCareApi.Infrastructure.Data.Migrations
{
    [DbContext(typeof(HealthCareDbContext))]
    [Migration("20250303094816_First")]
    partial class First
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PSBS.HealthCareApi.Domain.Medicine", b =>
                {
                    b.Property<Guid>("medicineId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("medicine_id");

                    b.Property<bool>("isDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("isDeleted");

                    b.Property<string>("medicineImage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("medicine_image");

                    b.Property<string>("medicineName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("medicine_name");

                    b.Property<Guid>("treatmentId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("treatment_id");

                    b.HasKey("medicineId");

                    b.HasIndex("treatmentId");

                    b.ToTable("Medicine");
                });

            modelBuilder.Entity("PSBS.HealthCareApi.Domain.PetHealthBook", b =>
                {
                    b.Property<Guid>("healthBookId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("healthBook_Id");

                    b.Property<Guid>("BookingServiceItemId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("BookingServiceItem_Id");

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<bool>("isDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("isDeleted");

                    b.Property<string>("medicineIds")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("medicine_Ids");

                    b.Property<DateTime?>("nextVisitDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("nextvisit_Date");

                    b.Property<string>("performBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("perform_By");

                    b.Property<DateTime?>("updatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.Property<DateTime>("visitDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("visit_Date");

                    b.HasKey("healthBookId");

                    b.ToTable("PetHealthBook");
                });

            modelBuilder.Entity("PSBS.HealthCareApi.Domain.Treatment", b =>
                {
                    b.Property<Guid>("treatmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("treatment_Id");

                    b.Property<bool>("isDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("isDeleted");

                    b.Property<string>("treatmentName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("treatment_Name");

                    b.HasKey("treatmentId");

                    b.ToTable("Treatment");
                });

            modelBuilder.Entity("PetHealthBookMedicine", b =>
                {
                    b.Property<Guid>("healthBookId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("medicineId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("healthBookId", "medicineId");

                    b.HasIndex("medicineId");

                    b.ToTable("PetHealthBookMedicine");
                });

            modelBuilder.Entity("PSBS.HealthCareApi.Domain.Medicine", b =>
                {
                    b.HasOne("PSBS.HealthCareApi.Domain.Treatment", "Treatment")
                        .WithMany("Medicines")
                        .HasForeignKey("treatmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Treatment");
                });

            modelBuilder.Entity("PetHealthBookMedicine", b =>
                {
                    b.HasOne("PSBS.HealthCareApi.Domain.PetHealthBook", null)
                        .WithMany()
                        .HasForeignKey("healthBookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PSBS.HealthCareApi.Domain.Medicine", null)
                        .WithMany()
                        .HasForeignKey("medicineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PSBS.HealthCareApi.Domain.Treatment", b =>
                {
                    b.Navigation("Medicines");
                });
#pragma warning restore 612, 618
        }
    }
}
