name: psbs_app_flutter
description: "A new Flutter project."
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  http: ^1.3.0
  image_picker: ^1.1.2
  shared_preferences: ^2.5.1
  cupertino_icons: ^1.0.8
  curved_navigation_bar: ^1.0.6
  fluttertoast: ^8.2.11
  dio: ^5.8.0+1
  flutter_html: ^3.0.0-beta.2
  flutter_quill: ^11.0.0
  flutter_quill_extensions: ^11.0.0
  intl: ^0.19.0
  flutter_localization: ^0.3.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
